# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import save_the_change.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Modified')),
                ('object_id', models.PositiveIntegerField()),
                ('link', models.CharField(max_length=1000, verbose_name='Video URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='Thumbnail')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
            bases=(save_the_change.mixins.SaveTheChange, models.Model),
        ),
    ]
