# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 15:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import save_the_change.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dishes', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodlands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Modified')),
                ('image', models.ImageField(upload_to=b'', verbose_name='Image')),
                ('alt_text', models.CharField(blank=True, max_length=100, null=True)),
                ('banner', models.BooleanField(default=False, verbose_name='Take this image for banner?')),
                ('published', models.BooleanField(default=False, verbose_name='Published?')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_images', to='dishes.Dish')),
            ],
            options={
                'verbose_name': 'Dish Image',
                'verbose_name_plural': 'Dish Images',
            },
            bases=(save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Modified')),
                ('object_id', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to=b'', verbose_name='Image')),
                ('alt_text', models.CharField(blank=True, max_length=100, null=True)),
                ('published', models.BooleanField(default=False, verbose_name='Published?')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_image', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='RestaurantImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Modified')),
                ('image', models.ImageField(upload_to=b'', verbose_name='Image')),
                ('alt_text', models.CharField(blank=True, max_length=100, null=True)),
                ('banner', models.BooleanField(default=False, verbose_name='Take this image for banner?')),
                ('published', models.BooleanField(default=False, verbose_name='Published?')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_image', to='foodlands.Restaurant')),
            ],
            options={
                'verbose_name': 'Restaurant Image',
                'verbose_name_plural': 'Restaurant Images',
            },
            bases=(save_the_change.mixins.SaveTheChange, models.Model),
        ),
    ]
