# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import save_the_change.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foodland_specifications', '0001_initial'),
        ('foodlands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Modified')),
                ('name', models.CharField(max_length=255, verbose_name='Dish Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=255, populate_from=b'name', unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('dish_image', models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='Dish Image ')),
                ('price', models.FloatField(default=0, help_text='Price of the Dish', verbose_name='Price')),
                ('dish_type', models.CharField(choices=[(b'v', 'VEG'), (b'n', 'NON-VEG')], default=b'n', max_length=1, verbose_name='Dish Type')),
                ('open_time', models.TimeField(blank=True, null=True, verbose_name='Open time')),
                ('close_time', models.TimeField(blank=True, null=True, verbose_name='Close time')),
                ('foodlands_rating', models.FloatField(db_index=True, default=0, verbose_name='Rating')),
                ('search_tags', models.TextField(blank=True, null=True, verbose_name='Search Tags')),
                ('published', models.BooleanField(default=True, verbose_name='Published?')),
                ('user_rating', models.FloatField(db_index=True, default=0, verbose_name='Rating')),
                ('tasted_count', models.PositiveIntegerField(default=0, verbose_name='Tasted Count')),
                ('favourite_count', models.PositiveIntegerField(default=0, verbose_name='Favourite Count')),
                ('recommend_count', models.PositiveIntegerField(default=0, verbose_name='Bookmark Count')),
                ('comments_count', models.PositiveIntegerField(default=0, verbose_name='Comments Count')),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('seo_description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('seo_keywords', models.TextField(blank=True, null=True, verbose_name='Keywords')),
                ('seo_image', models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='SEO Image')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foodland_specifications.Course', verbose_name=b'course')),
                ('cuisine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_cuisine', to='foodland_specifications.Cuisine')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foodlands.Restaurant')),
            ],
            options={
                'verbose_name': 'Dish',
                'verbose_name_plural': 'Dishes',
            },
            bases=(save_the_change.mixins.SaveTheChange, models.Model),
        ),
    ]
